### PR TITLE
fix(policies): skip policy enforcement only for Istio-init container

### PR DESCRIPTION
**Pull request by j-zimnowoda**
current annotation that is set by istio mutation will prevent complete pod to be checked on the
provided policies (allowedusers,capabilities and containerlimits). With this change it will only
skip validation for istio-init container

BREAKING CHANGE: This will cause the policies allowedusers/capabilities/containerlimits to work on
all pods that are injected by istio. This might prevent users for instance to update pods that are
running as root already.

## Checklist

- [x] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [x] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes.
- [x] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file.

### CODE REVIEW

**Comment by j-zimnowoda** [comment]
I consider this BREAKING CHANGE as a low risk, because policies enforcement was already performed for Deployments and Stateful Sets, Daemon Sets (so for those manifests before istio mutation web hook)

**Comment by Morriz** [comment]
Where is the previous PR from @bartusz01 where I elaborated on this issue?

**Comment by j-zimnowoda** [comment]
> Where is the previous PR from @bartusz01 where I elaborated on this issue?

there was no PR opened before

**Comment by bartusz01** [comment]
indeed, didnt create a PR yet, because I wanted to look into the Rego code. However, it can be merged already to fix the issue. I just now removed also the `container-limits` exception, since `istio-init` container is deployed with allowed resources.

**Review by bartusz01 — APPROVED** [review]

**Comment by Morriz** [comment]
Ok. Can we also take istio-proxy into account please? And not merge unfinished reviews @j-zimnowoda ?

**Comment by Morriz** [comment]
So may I ask why `istio-proxy` is not caught by gatekeeper now @bartusz01 ? Or is it and should it be added similarly?

**Comment by bartusz01** [comment]
Check the comments above! `istio-proxy` is validated and allowed, there is nothing in its securityContext that will force gatekeeper to deny the request, see here the `istio-proxy` security context:
```yaml
securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
```

**Comment by Morriz** [comment]
aha, it is made very strict since some versions ago then. I remember we had issues with it back when the exclusion mechanism was made. non-issue then. Awesome

**Pull request merged**
