### PR TITLE
feat: increase wait time for keycloak

### LINKED ISSUE #1474: Increase timeout for Keycloak to be ready during deployment
When deploying Otomi to some cloud hosting providers, the installation fails during the Keycloak setup (e.g. `wait-for-otomi-realm`). Most of the time, this is due to the updated DNS entries not being able to resolve (at all or in time). In some other cases, the certificate of Keycloak is rejected as self-signed.

Some of the DNS resolution issues are caused by configuration. However, increasing the timeout could account for some lag in the updates.

Additionally, users should be made aware of common configuration issues by adding a checklist of prerequisites to the installation docs, e.g. providing a valid email address when using Letsencypt, testing DNS beforehand (especially NS entries).

### PR DESCRIPTION
**Pull request by j-zimnowoda**
partially-fixes #1474
By increasing retries to 100, we increase waiting time up to 30 minutes for DNS records

### CODE REVIEW

**Review by srodenhuis — COMMENTED** [review]
The wait for will wait for the Keycloak realm to become available. The Keycloak realm is configured by the Keycloak Job. The Keycloak Job waits for keycloak to have a valid cert.  Would it not also be necessary to increase the retries of the Keycloak Job?

**Comment by srodenhuis** [comment]
Another observation: The job-keycloak will restart after 50 tries and wil try for another 50 times. The wait-for-otomi-realm however will not restart after 50 tries. I propose to increase the retries for the job-keycloak to 100 and 200 for the wait-for-otomi-realm

**Comment by j-zimnowoda** [comment]
> The wait for will wait for the Keycloak realm to become available. The Keycloak realm is configured by the Keycloak Job. The Keycloak Job waits for keycloak to have a valid cert. Would it not also be necessary to increase the retries of the Keycloak Job?

Thanks for valuable insights.
I was on assumption that keycloak job is using internal URL. However, I looked into tasks and it is not the case. I will first check if it is possible to use internal URL. Otherwise I will fallback to your proposed solution.

**Review by srodenhuis — APPROVED** [review]
200 TGTM

**Pull request merged**
