### PR TITLE
feat: allow adding new charts even if they are not defined in the schema spec

### PR DESCRIPTION
**Pull request by j-zimnowoda**
It is quite painful to provide values to otomi-values repo for new charts, because `otomi validate-values` will rise an error, e.g.:                                                                                         
```
[
  {
    keyword: 'additionalProperties',
    dataPath: '.charts',
    schemaPath: '#/properties/charts/additionalProperties',
    params: { additionalProperty: 'vault' },
    message: 'should NOT have additional properties'
  }
]
```

I would really appreciate if we can make schema more permissive for new charts names, so developers do not stumble on "chicken egg" problem and can provide working settings to values repo that can accompany PRs in otomi-core.

### CODE REVIEW

**Review by Morriz — COMMENTED** [review]
Why is that a problem? It is not blocking, is it? It is only telling that a schema is not containing that chart.  Also, this should not really be a problem once we get the backwards compatible schema solution delivered.
Seems like a fix to avoid warnings that are there for a reason.

**Comment by svatwork** [comment]
> because otomi validate-values will rise an error

Isn't that a good thing? I always thought that it's a prompt to extend the schema. 

> Also, this should not really be a problem once we get the backwards compatible schema solution delivered.

I don't understand this statement. Problems relating to new properties aren't included in #259?

**Comment by Morriz** [comment]
> > Also, this should not really be a problem once we get the backwards compatible schema solution delivered.
> 
> I don't understand this statement. Problems relating to new properties aren't included in #259?

Actually, now that you ask, how is 256 dealing with extraneous props? If an old schema is not expecting one, it will throw an error. We could let 256 simply remove props from the input values just because they don't exist, but then we have to remove all of the `additionalProperties` checks, as those will always be a problem for the old schemas.

I propose removing ALL of those lines.

**Comment by Morriz** [comment]
Approving this for one for now, and expecting another PR for the rest.

**Review by Morriz — APPROVED** [review]

**Review by svatwork — APPROVED** [review]

**Comment by svatwork** [comment]
> I propose removing ALL of those lines.

I agree.

> Approving this for one for now, and expecting another PR for the rest.

Let's include this in #259?

**Pull request merged**
