### PR TITLE
fix: setting ttl to 0 to remove jobs on completion

### PR DESCRIPTION
**Pull request by Morriz**

### CODE REVIEW

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
Have you tested it?
I tried to to create jobs with TTL `0` and `1` on AWS cluster and I do not see that controller removes them :(

**Comment by Morriz** [comment]
I am expecting them too be removed according to k8s docs, and I am not in the business of testing their code. We should file a bug if what we follow is not correct.

What does your test file look like?

**Comment by Morriz** [comment]
Also, that was added in 1.12. Can you investigate wether AWS has that enabled? I expect that to be GA by now, so I assumed it to be available. It must be, otherwise the controller would bork.

**Comment by Morriz** [comment]
You are right, can take a lot of time before this passes as beta or ga. Closing this PR.

**Pull request closed without merging**
