### PR TITLE
fix(config): change polling_interval to poller_interval_milliseconds

### PR DESCRIPTION
**Pull request by staticvoid255**
Fix for KES - polling_interval should be poller_interval_milliseconds

### CODE REVIEW

**Review by j-zimnowoda — COMMENTED** [review]
Checked with documentation. Looking good.
Since schema has changed I recommend adding a new entry in values-changes.yaml that indicates this `relocation`

**Comment by Morriz** [comment]
I don't think we should put units in the names of configuration, as the description/examples/regex already show what is expected. This goes the same for variables in code.

**Comment by Morriz** [comment]
no, please understand, I talked to the core dev and he wants to change the interval...

**Comment by Morriz** [comment]
That is why it is BAD PRACTICE to be overly specific in naming

**Comment by Morriz** [comment]
I sincerely hope you make good decisions in such matters in my absence. You may think it is nitpicking, but it is all about guarding the guide so that such poor decisions do not proliferate and incur unneeded work

**Comment by staticvoid255** [comment]
I would personally lean towards the name being as close to the actual name in the chart as possible so as not to insert ourselves too much between the user and underlying Helm chart

**Comment by Morriz** [comment]
This is about coding in general. Please get some courses on best practices and read coding style guides about variable naming etc. We also have the added limitation that bad choices are more impactful than variable naming: we expose configuration to users.

**Comment by staticvoid255** [comment]
Ok well your opinion on naming doesn't change the fact that you've used `POLLING_INTERVAL`  instead of `POLLER_INTERVAL_MILLISECONDS` and therefore aren't even targeting the actual value in the Helm chart.

**Comment by Morriz** [comment]
moot ;p

**Comment by staticvoid255** [comment]
I also think a unit change scenario doesn't apply here. There's no way the developers are going to change to say, seconds, without changing the name of the value - why would  they ever do so without changing `POLLER_INTERVAL_MILLISECONDS` to `POLLER_INTERVAL_SECONDS`? It's better in my opinion that the correspondence between our definitions and theirs be as close possible. In the case of a unit change It would be better practice to fall back to Helm defaults than applying the existing value under the new unit regime.

**Comment by Morriz** [comment]
nevermind, this is my mistake as I see a PR out of the blue not explaining this is actually a bug fix. I just see a PR that I reply to as code gatekeeper. It was introduced without a message what it is for, and used wording I did not recognize. I think I would have recognized "`POLLING_INTERVAL` should be `POLLER_INTERVAL_MILLISECONDS`".

My mistake to assume it was a suggestion.

**Comment by Morriz** [comment]
> I also think a unit change scenario doesn't apply here. There's no way the developers are going to change to say, seconds, without changing the name of the value - why would they ever do so without changing POLLER_INTERVAL_MILLISECONDS to POLLER_INTERVAL_SECONDS? It's better in my opinion that the correspondence between our definitions and theirs be as close possible. In the case of a unit change It would be better practice to fall back to Helm defaults than applying the existing value under the new unit regime.

I incorrectly assumed their choice was `POLLING_INTERVAL` (which, like prometheus' `duration`, could have been expressed like `1s` or even `1m`)

**Comment by Morriz** [comment]
FYI: I adopted this fix into main for next release (coming up)

**Pull request closed without merging**
