### PR TITLE
feat: go migrate

### PR DESCRIPTION
**Pull request by k7o**
Tool to help manage and implement incremental changes to the db structure.

### CODE REVIEW

**Comment by j-zimnowoda** [comment]
Hi @k7o. Thanks for contributing. We are eager to merge your PR.
Before merging, It seems that your PR file follows windows line termination style. If so could you convert it to linux style?

**Review by j-zimnowoda — COMMENTED** [review]
Hi @k7o. Thanks for contributing. We are eager to merge your PR.
Before merging, It seems that your PR file follows windows line termination style. If so could you convert it to linux style?

**Comment by k7o** [comment]
Hi @j-zimnowoda, I've changed the line termination to unix style.

**Review by j-zimnowoda — APPROVED** [review]
Great. Thanks

**Comment by j-zimnowoda** [comment]
@k7o the tool is available in `otomi/tools-db:v0.0.3`

**Pull request merged**
