### PR TITLE
feat: glasnostic

### PR DESCRIPTION
**Pull request by Morriz**
Installs glasnostic chart

### CODE REVIEW

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
Could you please create a user story for that PR and provide information about intent and use cases?

**Comment by Morriz** [comment]
Not necessary it's very clear what it does: it installs glasnostic. If you want to get to know their app, please visit https://glasnostic.com (you could have googled it easily)

**Comment by Morriz** [comment]
I do invite any reviewer to install it themselves and check if there are any issues.

**Comment by j-zimnowoda** [comment]
For reviewer, after deploying glasnotstic with Otomi go through workshop: https://docs.glasnostic.com/quickstart/sampleapp/

**Comment by j-zimnowoda** [comment]
@Morriz, could you make a demo to the team somewhere  next week ?

**Comment by Morriz** [comment]
Sure. Wednesday?

**Comment by j-zimnowoda** [comment]
Whenever you are ready. Just let us know.

**Comment by Morriz** [comment]
they keep updating their app based on my findings, but so far I haven't gotten it to work

**Comment by j-zimnowoda** [comment]
When it is ready please open PR.

**Pull request closed without merging**
