### PR TITLE
Linux workaround

### LINKED ISSUE #353: update otomi with workaround for docker run in linux
See last comments

### PR DESCRIPTION
**Pull request by svatwork**
Closes #353.

### CODE REVIEW

**Comment by Dunky13** [comment]
Can we please not work/make changes to the old CLI? Gives me a lot of overhead porting it.

**Comment by svatwork** [comment]
One line of code is overhead? The "old" CLI is still in use so how else can I solve this issue?

**Comment by svatwork** [comment]
Just add it and I will do it if the new cli is delivered...

**Review by Morriz — APPROVED** [review]

**Review by Dunky13 — APPROVED** [review]
Don't see the added value, as the new CLI will already have this, and can already be used. But for the sake of continuation, let's merge it.

**Pull request merged**
