### PR TITLE
fix: external secrets regression, missing team-admin values

### LINKED ISSUE #827: Flaky secrets syncing
**Describe the bug:** (a clear and concise description of what the bug is)
Following on from #743 

We are encountering flaky syncing of secrets that requires much of the time a manual restart of the KES pod to initiate a full sync of secrets between Vault and the cluster. We determined the cause to be the default poller interval being too short, resulting in too frequent requests to the kube-api and consequential hitting of the rate limit. This rate limiting is preventing new secrets from being automatically synced and a manual restart must be done to ensure proper syncing.

Furthermore, we found that adding a values file for the app in the values repo resulted in more errors regarding access rights and CRD's. Like I said before this is due to someone updating the image version of the app but not the Helm chart itself (even though they follow a common release schedule.

```➜  ~ ont -n vault logs -f kubernetes-external-secrets-685b59ff9b-stngd                                                                                                                                                >> team-ritense-otomi-aks-ont

> kubernetes-external-secrets@8.5.5 start /app
> ./bin/daemon.js

{"level":30,"message_time":"2022-06-21T14:41:03.958Z","pid":17,"hostname":"kubernetes-external-secrets-685b59ff9b-stngd","payload":{},"msg":"loading kube specs"}
{"level":30,"message_time":"2022-06-21T14:41:06.443Z","pid":17,"hostname":"kubernetes-external-secrets-685b59ff9b-stngd","payload":{},"msg":"successfully loaded kube specs"}
{"level":30,"message_time":"2022-06-21T14:41:06.445Z","pid":17,"hostname":"kubernetes-external-secrets-685b59ff9b-stngd","payload":{},"msg":"verifiying CRD is installed"}
{"level":50,"message_time":"2022-06-21T14:41:16.545Z","pid":17,"hostname":"kubernetes-external-secrets-685b59ff9b-stngd","payload":{},"msg":"CRD installation check failed, statusCode: undefined"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kubernetes-external-secrets@8.5.5 start: `./bin/daemon.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kubernetes-external-secrets@8.5.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-06-21T14_41_16_640Z-debug.log```

```
camunda                     2m44s       ERROR, secrets "camunda" is forbidden: User "system:serviceaccount:vault:kubernetes-external-secrets" cannot get resource "secrets" in API group "" in the namespace "team-utrecht"                     91d
fluxcd-tenant-key           2m42s       ERROR, secrets "fluxcd-tenant-key" is forbidden: User "system:serviceaccount:vault:kubernetes-external-secrets" cannot get resource "secrets" in API group "" in the namespace "team-utrecht"           91d
gitlab-helm-internal-repo   2m42s       ERROR, secrets "gitlab-helm-internal-repo" is forbidden: User "system:serviceaccount:vault:kubernetes-external-secrets" cannot get resource "secrets" in API group "" in the namespace "team-utrecht"   91d
oauth2-proxy                2m43s       ERROR, secrets "oauth2-proxy" is forbidden: User "system:serviceaccount:vault:kubernetes-external-secrets" cannot get resource "secrets" in API group "" in the namespace "team-utrecht"                7d23h
```

**To Reproduce**
Steps to reproduce the behavior:

1. Create an Otomi cluster
2. Clone the values repo
3. Add the following file as kubernetes-external-secrets.yaml or external-secrets.yaml (I do not like that both of these work):
```apps:
    kubernetes-external-secrets:
        enabled: true
        x: y
        _rawValues:
            env:
                POLLER_INTERVAL_MILLISECONDS: 300000```
5.  Run deploy pipeline
6. KES should come back with errors

To see the syncing issue specifically you will have to add many many secrets so as to hit the rate limit.


**Expected behavior:** (a clear and concise description of what you expected to happen)

Secrets should consistently sync without requiring manual restarting of the pod


**Versions:** (seen in console's `/settings`)

- 0.16.6


**Additional context:** (add any other context about the problem here)

We have observed this problem multiple times, and believe there is a deeper issue with Otomi management of the KES app. I am looking into ways to prove this. We have an unsustainable workaround in-place so recommend this be treated as high-priority.

### PR DESCRIPTION
**Pull request by Morriz**
fixes #827

### CODE REVIEW

**Comment by Morriz** [comment]
@staticvoid255 if you have code that is missing from this PR, please add it. I am kindly asking to diff what is here with what you have, both for learning purposes, as well as completion.

**Comment by staticvoid255** [comment]
Nothing that I put in that you haven't, but please describe the test you performed. Below are my thoughts which will prevent the environment breaking if deployed for GU:

- Deploy latest release of Otomi (or preferrably 0.16.6 like GU are using)
- Create a secret in Console
- Verify ExternalSecret is synced to a k8s secret
- Upgrade Otomi to this branch version
- (optional) Ensure kubernetes-external-secrets.yaml or external-secrets.yaml is created in the values repo
-  **(important)** Ensure that creating such a file does not break things
- Modify secret
- Ensure sync
- Create new secret
- Ensure sync

I cannot do the upgrade for GU until this path has been tested given how many new features will be added, so it is imperative that this test be performed. Please confirm results here.

**Comment by staticvoid255** [comment]
If it is still the case that adding kubernetes-external-secrets.yaml or external-secrets.yaml then running apply causes things to break, then it confirms something else that's in the back of my mind. So please do this step and confirm results.

**Comment by Morriz** [comment]
I did the tests and this PR does indeed result in secrets getting synced without errors.

**Comment by staticvoid255** [comment]
Great thanks! 👍

**Review by staticvoid255 — APPROVED** [review]
Great work

**Pull request merged**
