### PR TITLE
fix: increase memory limits and requests for kiali

### PR DESCRIPTION
**Pull request by j-zimnowoda**

### CODE REVIEW

**Comment by srodenhuis** [comment]
Did you also adjust defaults in API schema?

**Comment by j-zimnowoda** [comment]
> Did you also adjust defaults in API schema?

No, I have not. Thanks for reminder.

**Comment by srodenhuis** [comment]
I changed Kiali limits in API

**Review by srodenhuis — APPROVED** [review]
LGTM

**Pull request merged**
