### PR TITLE
fix: do not allow list all resources

### PR DESCRIPTION
**Pull request by j-zimnowoda**
Prevent listing resources beyond team namespace.

By performing `k get <resource>  -A -oyaml` command team member could access content of any resource.
Note: `list` gives exactly the same privileges as `get`.

## Checklist

- [x] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [x] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes.
- [x] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file.

### CODE REVIEW

**Review by diabhey — APPROVED** [review]

**Comment by Morriz** [comment]
Wow, does list give get? This is another role. Can you demonstrate that in isolation?

**Comment by j-zimnowoda** [comment]
> Wow, does list give get? This is another role. Can you demonstrate that in isolation?

It is known Kubernetes issue (I would call it "confusion by design" :P ). 
What do you want to isolate here?

**Comment by Morriz** [comment]
Anyway, this seems to not replace the role with something else, potentially breaking the required rbac for SA `default`...was this tested by using a token from that account and trying to deploy something?

**Comment by j-zimnowoda** [comment]
> Anyway, this seems to not replace the role with something else, potentially breaking the required rbac for SA `default`...was this tested by using a token from that account and trying to deploy something?

Of course

**Review by Morriz — COMMENTED** [review]
Is the ClusterRole "list" an existing one or created by us? If it is ours then why not remove that as well?

**Comment by j-zimnowoda** [comment]
> Is the ClusterRole "list" an existing one or created by us? If it is ours then why not remove that as well?

good point. now removed

**Pull request merged**
