### PR TITLE
feat: extract all defaults from schema and load profile defaults

### PR DESCRIPTION
**Pull request by Morriz**
This PR:

- pre-commit: extracts defaults from schema into `values/defaults.yaml`
- provides `otomi defaults [--all]`: When given `--all` it shows all schema defaults, else just the defaults around input values (requires ENV_DIR to be set).
- adds `cluster.profile = (small|medium|large)` (default small) which loads `values/profile-(small|medium|large).yaml` (NOTE: only `small` is provided in this PR as I want to discuss the other profiles with all of you first.)

known issues (which are not problematic and costly to solve):
- it only extracts provided defaults from `values-schema.yaml` (it does not yet set empty arrays or empty dicts, which are still left in `helmfile.d/snippets/defaults.yaml`)

### CODE REVIEW

**Comment by staticvoid255** [comment]
Really like this, but does it include values hardcoded into the .gotmpls? I know we are moving away from that, but I think if we are going to add this, then it should be followed up by significant effort to move hardcoded values to default.

**Comment by Morriz** [comment]
> Really like this, but does it include values hardcoded into the .gotmpls? I know we are moving away from that, but I think if we are going to add this, then it should be followed up by significant effort to move hardcoded values to default.

No, I moved size/perf related resources into our first profile: `values/profile-small.yaml`. Please check the updated description of this PR.

@srodenhuis using profiles for small/medium/large is rather arbitrary but might makes sense. I discussed this with @j-zimnowoda before and you, so I moved ahead with this. It is now a matter of filling in the medium+large files.

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
hi Maurice,

Thanks for consolidating values into profiles!

A bit too much is happening in this PR
Could you please make separate PR for 
1. using env_dir instead of ENV_DIR
2. remove kind
3. adding skiK8s parameter to hf command
4. and perhaps changes made in src/common/* It is not clear your intention

**Comment by Morriz** [comment]
Why so many separate PRs? Those are mostly all needed in here. Please

**Comment by Morriz** [comment]
I am done with this PR ;)

**Comment by j-zimnowoda** [comment]
@Morriz 
I fully support having cluster profiles, so defaults can be derived
However, I am against keeping any defaults in the schema as schema cannot cope with derived defaults.

In my humble opinion schema should be used only to validate input data. The default values should be derived and there should only one source of truth for the defaults.

**Comment by Morriz** [comment]
Can you elaborate? What do you see as problematic in the current setup?

**Comment by Morriz** [comment]
Schema defaults and derived values are a separate thing

**Comment by Morriz** [comment]
Defaults are static (own) and derived values use logic that involves multiple sources (composite).

**Comment by j-zimnowoda** [comment]
It would be beneficial for this review to extract the snapshot test to separate PR, so we can see how the changes in defaults impact the expected manifest output. 
This test would also enable all Developers to perform refactoring with confidence :)

**Comment by Morriz** [comment]
Go ahead @j-zimnowoda I am satisfied the way it is now

**Pull request closed without merging**
