### PR TITLE
fix: olm upgrade

### PR DESCRIPTION
**Pull request by Morriz**
## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

### CODE REVIEW

**Comment by Morriz** [comment]
This is also ready for merge @j-zimnowoda

**Comment by Morriz** [comment]
the reported conflicts don't exist in this branch' code

**Comment by j-zimnowoda** [comment]
> @j-zimnowoda here:
> 
> https://github.com/redkubes/otomi-core/blob/2edc53b8f91526aab8ae73027c90e84bafcfd6c8/upgrades.yaml#L47

Oh, cool did not notice it before. Could you resolve conflicts?

**Comment by Morriz** [comment]
> the reported conflicts don't exist in this branch' code

@j-zimnowoda I already stated that there are no conflicts in the code (GH err?). Please confirm and merge this PR please

**Review by j-zimnowoda — COMMENTED** [review]
There is an error during the upgrade
```
operation: kubectl replace -f charts/operator-lifecycle-manager/crds
2023-01-25T11:05:00.805Z otomi:global:error Error: Error from server (NotFound): error when replacing "charts/operator-lifecycle-manager/crds/0000_50_olm_00-olmconfigs.crd.yaml": customresourcedefinitions.apiextensions.k8s.io "olmconfigs.operators.coreos.com" not found
    at execute (/home/app/stack/dist/src/cmd/upgrade.js:34:39)
    exit code: 1
    at ChildProcess.<anonymous> (/home/app/stack/node_modules/zx/dist/bundle.cjs:15261:22)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

```

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
This PR needs to solve the upgrade issue.

**Review by j-zimnowoda — APPROVED** [review]

**Pull request merged**
