### PR TITLE
test: make project ID visible

### PR DESCRIPTION
**Pull request by j-zimnowoda**
The project-id was treated as a secret but it is not a secret.
After this change it will be possible to copy and paste scw k8s cluster creation command.

### CODE REVIEW

**Review by ElderMatt — APPROVED** [review]
LGTM

**Review by ElderMatt — CHANGES_REQUESTED** [review]
There are still other places in the code where we use `${{ secrets.SCW_DEFAULT_PROJECT_ID }}` Should theses also be changed to the hardcoded version? For example in the run command of create private network.

**Comment by j-zimnowoda** [comment]
> There are still other places in the code where we use `${{ secrets.SCW_DEFAULT_PROJECT_ID }}` Should theses also be changed to the hardcoded version? For example in the run command of create private network.

You are right, will fix it soon.

**Comment by j-zimnowoda** [comment]
not applicable anymore

**Pull request closed without merging**
