### PR TITLE
fix: admin services

### PR DESCRIPTION
**Pull request by Morriz**
Splits core ingress from team services (including admin).

NOTE: this is a destructive operation and team-ns-admin has to be removed beforehand. Migrating in `upgrades.yaml` of all the resources is really very hard, and not worth it imo.

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

### CODE REVIEW

**Comment by Morriz** [comment]
No design here, just refactoring

**Comment by Morriz** [comment]
We should not waste time on talk about PRs that refactor spaghetti code. Just review and test for regression in such cases.

**Review by j-zimnowoda — CHANGES_REQUESTED** [review]
Refactoring should not introduce breaking changes

**Comment by j-zimnowoda** [comment]
Author failed to indicate any business objectives.

**Comment by Morriz** [comment]
This PR makes most conditionals obsolete for core ingress (which was the team-ns-admin chart, now core- ingresd), and allows the deployment of a new team-ns-admin chart, which then behaves like the other team-ns-* charts: facilitate team services.

**Comment by Morriz** [comment]
So very important to make team ingress work consistently

**Comment by j-zimnowoda** [comment]
@Morriz still I would like to discuss this kind of changes before implementing them. I have sent you an invite.

**Pull request closed without merging**
