### PR TITLE
feat: skip context check if it is not set in values

### PR DESCRIPTION
**Pull request by j-zimnowoda**
Throw error on missing kube context configuration

### CODE REVIEW

**Comment by Morriz** [comment]
The check may not be bypassed because of missing values. This could potentially overwrite another cluster unintentionally. Values should be provided when `isCli`. (Maybe that can be used as I see no checks around context.)

**Comment by Morriz** [comment]
ok, I updated the check and another issue. Will push to this branch...

**Comment by Morriz** [comment]
So instead of laying I made it throw an error. I do think we could generate the value for it if it is not set during bootstrap, as it follows a convention.

**Comment by Morriz** [comment]
added creation part

**Review by Morriz — APPROVED** [review]
hope you approve @j-zimnowoda

**Comment by j-zimnowoda** [comment]
> hope you approve @j-zimnowoda

Yes, this is good idea. Thanks for review!

**Pull request merged**
